routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('mail', function ()
	{
		$data = [];
		Mail::send('emails.booking', $data, function($message)
		{
			$message->to('matt@cpdforteachers.com')
					->subject('It worked!');
		});
	});

Route::resource('courses', 'CourseController');
Route::get('courses/tags/{tag}', 'CourseController@showTagged');


Route::get('events', 'EventController@index');
Route::get('events/book/{id}', 'EventController@book');

Route::post('booking-requests', 'BookingRequestController@store');

Route::get('feed-events', 'FeedController@feedEvents');
Route::get('feed-courses', 'FeedController@feedCourses');
Route::get('tag-courses', 'FeedController@tagCourses');

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('title', 'Courses')

@section('content')
	<div class="container">
		@foreach ($courses as $course)
			<h1><a href='{{ route("courses.show", $course->slug) }}'>{{ ($course->title) }}</a></h1>
			<p>{{ ($course->summary) }}</p>
		@endforeach
	</div>
@endsection

resources/views/courses/show.blade.php
@extends('layouts.app')

@section('title', $course->title)

@section('content')

	<div class="container">
	    <h1>{{ $course->title }}</h1>
	    {!! $course->summary !!}
		{!! $course->content !!}
		<h2>Dates</h2>


		@foreach($events as $event)
			<h4>{{ $event['venue']['name'] }}</h4>
			<p>{{ $event->starts->format('l d') }} to {{ $event->ends->format('l d F Y') }} </p>
			<h4>£{{ $event->price }}</h4>
			<p><a href="/events/book/{{ $event->id }}" class="btn btn-primary" role="button">Book Now</a></p>
		@endforeach
	</div>

@endsection

@section('collections')
	<div class="container">
	<hr />
	<h4> Collections</h4>
		@foreach($course->tags as $tag)
			<p><a href="/courses/tags/{{ $tag['slug'] }}">{{ $tag['name'] }} courses</p>
		@endforeach
	</div>
@endsection

resources/views/courses/tags.blade.php
@extends('layouts.app')

@section('title', $tagname . ' Courses')

@section('content')
	<div class="container">
		@foreach ($courses as $course)
			<h1><a href='{{ route("courses.show", $course->slug) }}'>{{ ($course->title) }}</a></h1>
			<p>{{ ($course->summary) }}</p>
		@endforeach
	</div>
@endsection